; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega8-example-Decoded-Keys]
platform = atmelavr
board = ATmega8
;framework = arduino

build_flags =
    -DF_CPU=8000000UL

; فقط لایبرری + مثال خاص
build_src_filter = +<../examples/Decoded-Keys/> +<../src/> +<../lib/>
 

[env:ATmega8-example-Decoded-Serial]
platform = atmelavr
board = ATmega8
;framework = arduino

build_flags =
    -DF_CPU=8000000UL

; فقط لایبرری + مثال خاص
build_src_filter = +<../examples/Decoded-Serial/> +<../src/> +<../lib/>

[env:ATmega32-example-EV1527_Encoder]
platform = atmelavr
board = ATmega32
;framework = arduino

build_flags =
    -DF_CPU=8000000UL

; فقط لایبرری + مثال خاص
build_src_filter = +<../examples/EV1527_Encoder/> +<../src/> +<../lib/>